name: Networking Stack & Approval

on:
  push:
    branches:
      - feat/networking-flow
      - master
    paths-ignore:
      - 'charts/**'

  pull_request:
    branches:
      - master
      # - feat/networking-flow
    paths-ignore:
      - 'charts/**'

permissions:
  id-token: write
  contents: write

jobs:
  detect-networking-changes:
    runs-on: ubuntu-latest
    outputs:
      requires_approval: ${{ steps.detect.outputs.requires_approval }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Environment Variables
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            ENVIRONMENT="${{ github.ref_name }}"
          else
            ENVIRONMENT="${{ github.event.pull_request.base.ref }}"
          fi

          echo "Deployment Environment: $ENVIRONMENT"
          echo "ENV_PREFIX: $ENVIRONMENT"
            
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Install AWS CDK
        run: npm install -g aws-cdk
      
      - name: Install dependencies
        run: npm install
      
      - name: cdk diff networking
        id: detect
        run: |
          DIFF_OUTPUT=$(cdk diff NetworkStack || true)
          echo "$DIFF_OUTPUT"
          
          if [[ -z "$DIFF_OUTPUT" || "$DIFF_OUTPUT" == *"There were no differences"* ]]; then
            echo "No changes detected in NetworkingStack"
            echo "requires_approval=false" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected in NetworkingStack"
            echo "requires_approval=true" >> "$GITHUB_OUTPUT"
          fi

  request-approval:
    needs: detect-networking-changes
    if: needs.detect-networking-changes.outputs.requires_approval == 'true'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    outputs:
      deployment_approved: ${{ steps.set_approval.outputs.deployment_approved }}
    steps:
      - name: Manual Workflow Approval
        id: approval
        uses: trstringer/manual-approval@v1.9.1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: Ram1814
          minimum-approvals: 1
          issue-title: "Approve Networking Changes"
          issue-body: "Please approve or deny the deployment of networking changes."

      - name: Check Approval Status
        id: set_approval
        run: |
          if [[ "${{ steps.approval.outcome }}" == "success" ]]; then
            echo "Manual approval succeeded"
            echo "deployment_approved=true" >> "$GITHUB_OUTPUT"
          else
            echo "Manual approval failed"
            echo "deployment_approved=false" >> "$GITHUB_OUTPUT"
          fi

  status-check:
    needs: 
      - detect-networking-changes
      - request-approval
    if: always()
    runs-on: ubuntu-latest
    outputs:
      proceed_with_deployment: ${{ steps.decision.outputs.proceed_with_deployment }}
    steps:
      - name: Determine network check result
        id: decision
        run: |
          requires_approval="${{ needs.detect-networking-changes.outputs.requires_approval }}"
          deployment_approved="${{ needs.request-approval.outputs.deployment_approved }}"

          echo "requires_approval: $requires_approval"
          echo "deployment_approved: $deployment_approved"

          if [[ "$requires_approval" == "false" ]]; then
            echo "No approval needed, proceeding with deployment."
            echo "proceed_with_deployment=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          if [[ "$requires_approval" == "true" && "$deployment_approved" == "true" ]]; then
            echo "Approval granted, proceeding with deployment."
            echo "proceed_with_deployment=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "Approval denied or pending! Skipping deployment."
          echo "proceed_with_deployment=false" >> "$GITHUB_OUTPUT"
          exit 1
          
  deploy-service:
    needs: status-check
    if: needs.status-check.outputs.proceed_with_deployment == 'true'
    uses: ./.github/workflows/service-deployment.yml
    with:
      environment: ${{ github.ref_name }}
