name: Service Deployment (Feature)

on:
  workflow_run:
    workflows: ["Networking Stack & Approval"]
    types:
      - completed
    # branches:
    #   - feat/networking-flow

  push:
    branches:
      - feat/networking-flow
    paths-ignore:
      - 'charts/**'

  pull_request:
    branches:
      - feat/networking-flow
    paths-ignore:
      - 'charts/**'

permissions:
  id-token: write
  contents: write

jobs:
  deploy-service:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' || 
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
     # ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Determine Environment
        run: |
          if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            ENV="${{ github.event.workflow_run.head_branch }}"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            ENV="${{ github.event.pull_request.base.ref }}"
          else
            ENV="${{ github.ref_name }}"
          fi
          echo "ENV_PREFIX=$ENV" >> $GITHUB_ENV
          echo "Environment resolved: $ENV"

      - name: Checkout the correct branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.ENV_PREFIX }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Install AWS CDK
        run: npm install -g aws-cdk
      
      - name: Install dependencies
        run: npm install
      
      - name: Deploy ServiceStack
        run: cdk deploy ServiceStack --require-approval never
