name: Service Deployment

on:
  workflow_run:
    workflows: ["Networking Stack & Approval"]
    types:
      - completed

  pull_request:
    branches:
      - feat/networking-flow
    paths-ignore:
      - 'charts/**'

permissions:
  id-token: write
  contents: write

jobs:
  deploy-service:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'pull_request' && needs.networking-status.outputs.networking_done == 'true')
    needs: networking-status
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Install AWS CDK
        run: npm install -g aws-cdk
      
      - name: Install dependencies
        run: npm install
      
      - name: Deploy ServiceStack
        run: cdk deploy ServiceStack --require-approval never

  networking-status:
    runs-on: ubuntu-latest
    outputs:
      networking_done: ${{ steps.check.outputs.networking_done }}
    steps:
      - name: Check Networking Stack Completion
        id: check
        run: |
          echo "Networking Stack has been successfully deployed"
          echo "networking_done=true" >> "$GITHUB_OUTPUT"
